POST http://localhost:7071/api/CreateEvent
Content-Type: application/json

{
  "title": " Grad Girls Meet and Greet ",
  "date": "2026-01-14T09:00:00Z ",
  "location": "AGL Melbourne"
}


### Get all events
GET http://localhost:7071/api/GetEvents