
### LIVE API URLS
@baseUrl = https://event-api-wic-czdvc8bwfsb7drag.australiaeast-01.azurewebsites.net/api

### Get all events (Live)
GET {{baseUrl}}/getevents

### Create an event (Live)
POST {{baseUrl}}/createevent
Content-Type: application/json

{
    "id": "test-old-id-999",
    "title": "Old Retro Party",
    "date": "2020-01-01T00:00:00.000Z",
    "location": "Memory Lane"
}

### Manually Trigger CleanUpOldEvents (Local)
POST http://localhost:7071/admin/functions/CleanupOldEvents
Content-Type: application/json

{
    "input": "{}"
}


### Get all events
GET http://localhost:7071/api/GetEvents


### Test RegisterUser (Local)
POST http://localhost:7071/api/RegisterUser
Content-Type: application/json

{
    "email": "nat.test@example.com",
    "eventId": "9a337808-4894-4a35-95aa-90f79c0f80ad"
}

### Test RegisterUser with missing data (Should fail)
POST http://localhost:7071/api/RegisterUser
Content-Type: application/json

{
    "email": " "
}