
### LIVE API URLS
@baseUrl = https://event-api-wic-czdvc8bwfsb7drag.australiaeast-01.azurewebsites.net/api

### Get all events (Live)
GET {{baseUrl}}/getevents

### Create an event (Live)
POST {{baseUrl}}/createevent
Content-Type: application/json

{
    "title": "Cloud Success Celebration",
    "date": "2026-01-14T10:00:00Z",
    "location": "Internet"
}



POST http://localhost:7071/api/CreateEvent
Content-Type: application/json

{
  "title": " Grad Girls Meet and Greet ",
  "date": "2026-01-14T09:00:00Z ",
  "location": "AGL Melbourne"
}


### Get all events
GET http://localhost:7071/api/GetEvents


